import { Member, Project, Settings, Task } from "./types";

// Datos iniciales en memoria (semilla)

export const seedMembers: Member[] = [
  {
    userId: "u1",
    name: "Maria Garcia",
    email: "maria@example.com",
    role: "Frontend Developer",
    position: "Senior",
    birthdate: "1994-03-12",
    phone: "987654321",
    projectId: "p1",
    isActive: true,
  },
  {
    userId: "u2",
    name: "Juan Perez",
    email: "juan@example.com",
    role: "Backend Developer",
    position: "Senior",
    birthdate: "1991-07-08",
    phone: "987111222",
    projectId: "p4",
    isActive: true,
  },
  {
    userId: "u3",
    name: "Ana Lopez",
    email: "ana@example.com",
    role: "UI/UX Designer",
    position: "Semi Senior",
    birthdate: "1996-11-23",
    phone: "987333444",
    projectId: "p2",
    isActive: false,
  },
  {
    userId: "u4",
    name: "Carlos Ruiz",
    email: "carlos@example.com",
    role: "DevOps Engineer",
    position: "Senior",
    birthdate: "1989-01-30",
    phone: "987555666",
    projectId: "p4",
    isActive: true,
  },
  {
    userId: "u5",
    name: "Laura Martinez",
    email: "laura@example.com",
    role: "Project Manager",
    position: "Lead",
    birthdate: "1988-09-05",
    phone: "987777888",
    projectId: "p1",
    isActive: true,
  },
];

export const seedProjects: Project[] = [
  {
    id: "p1",
    title: "E-commerce Platform",
    description: "Plataforma de comercio electronico con Next.js",
    status: "En progreso",
    progress: 65,
    category: "Desarrollo Web",
    priority: "Alta",
    memberIds: ["u1", "u5"],
  },
  {
    id: "p2",
    title: "Mobile App",
    description: "Aplicacion movil con React Native",
    status: "En revision",
    progress: 90,
    category: "Desarrollo Mobile",
    priority: "Media",
    memberIds: ["u3"],
  },
  {
    id: "p3",
    title: "Dashboard Analytics",
    description: "Panel de analisis con visualizaciones",
    status: "Planificado",
    progress: 20,
    category: "Desarrollo Web",
    priority: "Media",
    memberIds: [],
  },
  {
    id: "p4",
    title: "API Gateway",
    description: "Microservicios con Node.js",
    status: "En progreso",
    progress: 45,
    category: "Desarrollo Web",
    priority: "Alta",
    memberIds: ["u2", "u4"],
  },
  {
    id: "p5",
    title: "Design System",
    description: "Libreria de componentes reutilizables",
    status: "Completado",
    progress: 100,
    category: "Diseno",
    priority: "Baja",
    memberIds: ["u3"],
  },
  {
    id: "p6",
    title: "Marketing Website",
    description: "Sitio web institucional",
    status: "En progreso",
    progress: 75,
    category: "Marketing",
    priority: "Media",
    memberIds: ["u1"],
  },
];

export const seedTasks: Task[] = [
  {
    id: "t1",
    description: "Implementar autenticacion",
    projectId: "p1",
    status: "En progreso",
    priority: "Alta",
    userId: "u1",
    dateline: "2025-11-15",
  },
  {
    id: "t2",
    description: "Disenar pantalla de perfil",
    projectId: "p2",
    status: "Pendiente",
    priority: "Media",
    userId: "u3",
    dateline: "2025-11-20",
  },
  {
    id: "t3",
    description: "Configurar CI/CD",
    projectId: "p4",
    status: "Completado",
    priority: "Alta",
    userId: "u4",
    dateline: "2025-11-10",
  },
  {
    id: "t4",
    description: "Optimizar queries SQL",
    projectId: "p1",
    status: "En progreso",
    priority: "Urgente",
    userId: "u2",
    dateline: "2025-11-12",
  },
  {
    id: "t5",
    description: "Documentar API endpoints",
    projectId: "p4",
    status: "Pendiente",
    priority: "Baja",
    userId: "u5",
    dateline: "2025-11-25",
  },
  {
    id: "t6",
    description: "Crear componentes de tablas",
    projectId: "p5",
    status: "Completado",
    priority: "Media",
    userId: "u3",
    dateline: "2025-10-28",
  },
  {
    id: "t7",
    description: "Integrar pasarela de pagos",
    projectId: "p1",
    status: "Pendiente",
    priority: "Urgente",
    userId: "u1",
    dateline: "2025-12-02",
  },
  {
    id: "t8",
    description: "Pruebas e2e con Playwright",
    projectId: "p2",
    status: "Pendiente",
    priority: "Media",
    userId: "u3",
    dateline: "2025-12-05",
  },
  {
    id: "t9",
    description: "Configurar despliegue en Vercel",
    projectId: "p6",
    status: "En progreso",
    priority: "Alta",
    userId: "u4",
    dateline: "2025-11-29",
  },
  {
    id: "t10",
    description: "Maquetar landing institucional",
    projectId: "p6",
    status: "Completado",
    priority: "Baja",
    userId: "u1",
    dateline: "2025-11-05",
  },
  {
    id: "t11",
    description: "Definir esquema de base de datos",
    projectId: "p4",
    status: "Completado",
    priority: "Alta",
    userId: "u2",
    dateline: "2025-10-30",
  },
  {
    id: "t12",
    description: "Investigar metricas de analitica",
    projectId: "p3",
    status: "Pendiente",
    priority: "Media",
    userId: "u5",
    dateline: "2025-12-10",
  },
];

export const seedSettings: Settings = {
  organizationName: "TECSUP Software Factory",
  language: "es",
  timezone: "America/Lima",
  emailNotifications: true,
  pushNotifications: false,
  weeklyDigest: true,
  defaultPriority: "Media",
};
